// Shared restaurant data loader for the FoodMatch public website.
//
// The marketing/SEO website and the React app must show the SAME restaurants
// with the SAME slugs (so /valencia/<slug> on the web and /restaurant/<slug>
// in the app line up). Rather than duplicate the dataset, we parse the app's
// generated seed file (frontend/src/data/seedRestaurants.ts) at build time.
//
// The seed file is a plain `export const SEED_RESTAURANTS = [ {...} ]` of
// object literals with stable, simple formatting (it is itself generated by
// frontend/scripts/genSeed.mjs). We extract the fields the website needs with
// a light, well-bounded parse. This is a build-time script, never shipped.

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SEED_PATH = resolve(__dirname, '../../frontend/src/data/seedRestaurants.ts')

// --- tiny field extractors over a single object-literal block ---

function str(block, key) {
  const m = block.match(new RegExp(`${key}: '((?:[^'\\\\]|\\\\.)*)'`))
  return m ? m[1].replace(/\\'/g, "'") : undefined
}
function num(block, key) {
  const m = block.match(new RegExp(`${key}: (-?[0-9.]+)`))
  return m ? Number(m[1]) : undefined
}
function bool(block, key) {
  const m = block.match(new RegExp(`${key}: (true|false)`))
  return m ? m[1] === 'true' : undefined
}
function strArray(block, key) {
  const m = block.match(new RegExp(`${key}: \\[([^\\]]*)\\]`))
  if (!m) return []
  return [...m[1].matchAll(/'((?:[^'\\]|\\.)*)'/g)].map((x) => x[1].replace(/\\'/g, "'"))
}

/** Parse the seed file into an array of plain restaurant objects. */
export function loadRestaurants() {
  const src = readFileSync(SEED_PATH, 'utf8')
  // Split into object-literal blocks. Each entry starts with `id: '...'`.
  const blocks = src.split(/\n\s{2}\{\n/).slice(1)
  const out = []
  for (const raw of blocks) {
    const block = raw.split(/\n\s{2}\},/)[0]
    const id = str(block, 'id')
    const slug = str(block, 'slug')
    if (!id || !slug) continue
    const lateNight = /standardOpening\(true\)/.test(block)
    const brunch = /brunchHours\(\)/.test(block)
    out.push({
      id,
      slug,
      name: str(block, 'name'),
      description: str(block, 'description'),
      cuisine: str(block, 'cuisine'),
      secondaryCuisines: strArray(block, 'secondaryCuisines'),
      tags: strArray(block, 'tags'),
      vibe: strArray(block, 'vibe'),
      bestFor: strArray(block, 'bestFor'),
      area: str(block, 'area'),
      city: str(block, 'city') || 'Valencia',
      address: str(block, 'address'),
      priceLevel: num(block, 'priceLevel') ?? 2,
      averageSpend: num(block, 'averageSpend') ?? 20,
      rating: num(block, 'rating') ?? 4,
      reviewCount: num(block, 'reviewCount') ?? 0,
      instagram: str(block, 'instagram'),
      phone: str(block, 'phone'),
      hours: brunch ? 'brunch' : lateNight ? 'late' : 'standard',
      vegetarianFriendly: bool(block, 'vegetarianFriendly') ?? false,
      veganFriendly: bool(block, 'veganFriendly') ?? false,
      glutenFreeOptions: bool(block, 'glutenFreeOptions') ?? false,
      isPartner: bool(block, 'isPartner') ?? false,
    })
  }
  return out
}

// Human-readable opening hours per "hours" kind, mirroring the app's
// standardOpening / brunchHours builders. Used for display + JSON-LD.
export const OPENING_HOURS = {
  standard: {
    label: { es: 'Lun a Dom · 13:00 - 23:30', en: 'Mon to Sun · 1:00pm - 11:30pm' },
    // schema.org openingHours format
    spec: ['Mo-Th 13:00-23:30', 'Fr-Sa 13:00-24:00', 'Su 13:00-17:00'],
  },
  late: {
    label: { es: 'Lun a Dom · 13:00 - 02:00', en: 'Mon to Sun · 1:00pm - 2:00am' },
    spec: ['Mo-Th 13:00-01:30', 'Fr-Sa 13:00-02:30', 'Su 13:00-17:00'],
  },
  brunch: {
    label: { es: 'Lun a Dom · 08:30 - 18:00', en: 'Mon to Sun · 8:30am - 6:00pm' },
    spec: ['Mo-Fr 08:30-18:00', 'Sa-Su 09:00-19:00'],
  },
}

// Cuisine display labels (ES/EN). Falls back to the raw key.
export const CUISINE_LABEL = {
  'Spanish tapas': { es: 'Tapas', en: 'Spanish tapas' },
  paella: { es: 'Arroces y paella', en: 'Paella & rice' },
  'menú del día': { es: 'Menú del día', en: 'Menu of the day' },
  sushi: { es: 'Sushi', en: 'Sushi' },
  burgers: { es: 'Hamburguesas', en: 'Burgers' },
  pizza: { es: 'Pizza', en: 'Pizza' },
  pasta: { es: 'Pasta', en: 'Pasta' },
  'healthy bowls': { es: 'Saludable', en: 'Healthy bowls' },
  vegan: { es: 'Vegano', en: 'Vegan' },
  vegetarian: { es: 'Vegetariano', en: 'Vegetarian' },
  brunch: { es: 'Brunch', en: 'Brunch' },
  coffee: { es: 'Cafetería', en: 'Coffee' },
  bar: { es: 'Bar', en: 'Bar' },
  Mexican: { es: 'Mexicana', en: 'Mexican' },
  Indian: { es: 'India', en: 'Indian' },
  'Asian fusion': { es: 'Fusión asiática', en: 'Asian fusion' },
  Mediterranean: { es: 'Mediterránea', en: 'Mediterranean' },
  seafood: { es: 'Marisco y pescado', en: 'Seafood' },
  steak: { es: 'Carnes a la brasa', en: 'Steak & grill' },
}

export function cuisineLabel(cuisine, lang) {
  return (CUISINE_LABEL[cuisine] && CUISINE_LABEL[cuisine][lang]) || cuisine
}

// Area display (the app uses "City center" / "Marina / beach"; localise).
export const AREA_LABEL = {
  Ruzafa: { es: 'Ruzafa', en: 'Ruzafa' },
  'El Carmen': { es: 'El Carmen', en: 'El Carmen' },
  Canovas: { es: 'Cánovas', en: 'Cánovas' },
  Benimaclet: { es: 'Benimaclet', en: 'Benimaclet' },
  'City center': { es: 'Centro', en: 'City center' },
  'Marina / beach': { es: 'Marina y playa', en: 'Marina & beach' },
}

export function areaLabel(area, lang) {
  return (AREA_LABEL[area] && AREA_LABEL[area][lang]) || area
}
